modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/an1by/SimpleWhitelist/issues"
[[mods]]
modId = "simplewhitelist"
version = "${mod_version}"
displayName = "SimpleWhitelist"
updateJSONURL = "https://modrinth.com/plugin/simplewhitelist/versions?l=forge"
displayURL = "https://modrinth.com/plugin/simplewhitelist"
logoFile = "icon.png"
authors = "An1by"
description = '''Simple whitelist system for your server'''
displayTest = "NONE"

[[dependencies.simplewhitelist]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "SERVER"

[[dependencies.simplewhitelist]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "SERVER"
