enabled: true
case_sensitive: false
messages:
  no_permission: "<red>Not enough permissions!</red>"
  invalid_arguments: "<red>Invalid arguments!</red>"
  need_player: "<red>Player's name is needed!</red>"
  already_whitelisted: "<red><name> is already whitelisted!</red>"
  not_in_whitelist: "<red>You are not in simple whitelist!</red>"
  empty: "Empty"
command_messages:
  add: "<green><name> added to whitelist!</green>"
  remove: "<green><name> removed from whitelist!</green>"
  list: "<gold>In whitelist: </gold><yellow><list></yellow>"
  enable: "<green>Whitelist enabled!</green>"
  disable: "<red>Whitelist disabled!</red>"
  reload: "<green>Reload success!</green>"
  help: |
    <dark_purple>{ <light_purple>SimpleWhitelist<dark_purple> }
    <yellow>:: <white>/swl add <aqua><name></aqua></white>
    <yellow>:: <white>/swl remove <aqua><name></aqua></white>
    <yellow>:: <white>/swl enable</white>
    <yellow>:: <white>/swl disable</white>
    <yellow>:: <white>/swl reload</white>
    <yellow>:: <white>/swl help</white>
